import { hashPassword } from '../auth/crypto.js';
import type {
  User,
  Project,
  Task,
  Team,
  Column,
  TimesheetEntry,
  Activity,
  Notification,
  SystemSettings,
  KanbrawlData,
} from '../types.js';

export const DEFAULT_COLUMNS: Column[] = [
  { name: 'Backlog', sortBy: 'priority', sortOrder: 'asc' },
  { name: 'To Do', sortBy: 'priority', sortOrder: 'asc' },
  { name: 'In Progress', sortBy: 'updated', sortOrder: 'desc' },
  { name: 'Blocked', sortBy: 'priority', sortOrder: 'asc' },
  { name: 'Review', sortBy: 'updated', sortOrder: 'desc' },
  { name: 'Done', sortBy: 'updated', sortOrder: 'desc' },
];

export function generateSeedData(): KanbrawlData<User> {
  const now = new Date();
  const pastDays = (days: number) =>
    new Date(now.getTime() - days * 24 * 60 * 60 * 1000).toISOString();
  const futureDays = (days: number) =>
    new Date(now.getTime() + days * 24 * 60 * 60 * 1000).toISOString();
  const dateOnly = (daysOffset: number) => {
    const d = new Date(now.getTime() + daysOffset * 24 * 60 * 60 * 1000);
    return d.toISOString().split('T')[0];
  };

  // ── Seed Users with hashed passwords ──
  const orgAdminAuth = hashPassword('admin123', 'seed_salt_orgadmin');
  const pmAuth = hashPassword('pm123', 'seed_salt_pm');
  const leadAuth = hashPassword('lead123', 'seed_salt_lead');
  const empAuth = hashPassword('emp123', 'seed_salt_emp');
  const devAuth = hashPassword('dev123', 'seed_salt_dev');
  const viewerAuth = hashPassword('view123', 'seed_salt_viewer');

  const users: User[] = [
    {
      id: 'usr-org-admin',
      name: 'Eleanor Sterling',
      email: 'orgadmin@enterprise.com',
      passwordHash: orgAdminAuth.hash,
      salt: orgAdminAuth.salt,
      role: 'org_admin',
      organizationId: 'org-global',
      teamId: 'team-core',
      status: 'active',
      title: 'VP of Engineering & Organization Admin',
      avatarColor: '#3d6b5e',
      createdAt: pastDays(100),
      lastActive: pastDays(0),
    },
    {
      id: 'usr-pm-marcus',
      name: 'Marcus Holloway',
      email: 'pm@enterprise.com',
      passwordHash: pmAuth.hash,
      salt: pmAuth.salt,
      role: 'project_manager',
      organizationId: 'org-global',
      teamId: 'team-apps',
      status: 'active',
      title: 'Senior Project Manager',
      avatarColor: '#6a3d9a',
      createdAt: pastDays(90),
      lastActive: pastDays(0),
    },
    {
      id: 'usr-lead-sarah',
      name: 'Sarah Jenkins',
      email: 'lead@enterprise.com',
      passwordHash: leadAuth.hash,
      salt: leadAuth.salt,
      role: 'team_lead',
      organizationId: 'org-global',
      teamId: 'team-apps',
      status: 'active',
      title: 'Principal Architect & Tech Lead',
      avatarColor: '#b15928',
      createdAt: pastDays(80),
      lastActive: pastDays(0),
    },
    {
      id: 'usr-emp-david',
      name: 'David Chen',
      email: 'employee@enterprise.com',
      passwordHash: empAuth.hash,
      salt: empAuth.salt,
      role: 'employee',
      organizationId: 'org-global',
      teamId: 'team-apps',
      status: 'active',
      title: 'Senior Fullstack Engineer',
      avatarColor: '#1f78b4',
      createdAt: pastDays(70),
      lastActive: pastDays(0),
    },
    {
      id: 'usr-dev-priya',
      name: 'Priya Sharma',
      email: 'dev@enterprise.com',
      passwordHash: devAuth.hash,
      salt: devAuth.salt,
      role: 'employee',
      organizationId: 'org-global',
      teamId: 'team-data',
      status: 'active',
      title: 'Backend Systems Engineer',
      avatarColor: '#33a02c',
      createdAt: pastDays(60),
      lastActive: pastDays(1),
    },
    {
      id: 'usr-viewer-rachel',
      name: 'Rachel Adams',
      email: 'viewer@enterprise.com',
      passwordHash: viewerAuth.hash,
      salt: viewerAuth.salt,
      role: 'viewer',
      organizationId: 'org-global',
      status: 'active',
      title: 'Stakeholder & Product Auditor',
      avatarColor: '#7f7f7f',
      createdAt: pastDays(50),
      lastActive: pastDays(2),
    },
  ];

  // ── Teams ──
  const teams: Team[] = [
    {
      id: 'team-core',
      name: 'Core Platform & Infrastructure',
      organizationId: 'org-global',
      leadId: 'usr-org-admin',
      leadName: 'Eleanor Sterling',
      memberIds: ['usr-org-admin'],
      description: 'Responsible for core cloud runtime, security, microservices baseline, and identity.',
      createdAt: pastDays(100),
    },
    {
      id: 'team-apps',
      name: 'Digital Products Team',
      organizationId: 'org-global',
      leadId: 'usr-lead-sarah',
      leadName: 'Sarah Jenkins',
      memberIds: ['usr-lead-sarah', 'usr-emp-david', 'usr-pm-marcus'],
      description: 'Builds customer-facing web applications, mobile gateways, and checkout platforms.',
      createdAt: pastDays(90),
    },
    {
      id: 'team-data',
      name: 'Data & Analytics Engineering',
      organizationId: 'org-global',
      leadId: 'usr-lead-sarah',
      leadName: 'Sarah Jenkins',
      memberIds: ['usr-dev-priya', 'usr-emp-david'],
      description: 'Maintains transaction pipelines, ML telemetry models, and healthcare audit pipelines.',
      createdAt: pastDays(80),
    },
  ];

  // ── Projects ──
  const projects: Project[] = [
    {
      id: 'proj-ecom',
      name: 'E-Commerce Platform',
      key: 'ECOM',
      description: 'Next-generation omni-channel checkout, order management, payment integration, and inventory sync.',
      organizationId: 'org-global',
      managerId: 'usr-pm-marcus',
      managerName: 'Marcus Holloway',
      teamIds: ['team-apps'],
      status: 'in_progress',
      priority: 'P0',
      riskLevel: 'medium',
      riskScore: 48,
      riskFactors: ['Payment gateway sandbox certification delayed', 'High dependency count on auth microservice'],
      startDate: pastDays(45),
      targetDate: futureDays(25),
      budgetHours: 640,
      createdAt: pastDays(45),
      updatedAt: pastDays(1),
    },
    {
      id: 'proj-hosp',
      name: 'Hospital Management System',
      key: 'HOSP',
      description: 'HIPAA-compliant Electronic Health Records (EHR), outpatient scheduling, triage queue, and pharmacy inventory.',
      organizationId: 'org-global',
      managerId: 'usr-pm-marcus',
      managerName: 'Marcus Holloway',
      teamIds: ['team-core', 'team-data'],
      status: 'in_progress',
      priority: 'P0',
      riskLevel: 'high',
      riskScore: 78,
      riskFactors: ['3 overdue compliance validation tasks', 'HL7 FHIR integration blocked by vendor certificate'],
      startDate: pastDays(60),
      targetDate: futureDays(10),
      budgetHours: 920,
      createdAt: pastDays(60),
      updatedAt: pastDays(0),
    },
    {
      id: 'proj-mbank',
      name: 'Mobile Banking Application',
      key: 'MBANK',
      description: 'Retail banking iOS and Android solution featuring biometric auth, instant P2P transfers, and card controls.',
      organizationId: 'org-global',
      managerId: 'usr-pm-marcus',
      managerName: 'Marcus Holloway',
      teamIds: ['team-apps'],
      status: 'in_progress',
      priority: 'P1',
      riskLevel: 'low',
      riskScore: 22,
      riskFactors: ['Velocity on track', 'Biometric auth module passed security review ahead of schedule'],
      startDate: pastDays(30),
      targetDate: futureDays(45),
      budgetHours: 500,
      createdAt: pastDays(30),
      updatedAt: pastDays(2),
    },
    {
      id: 'proj-campus',
      name: 'College Management Portal',
      key: 'CAMPUS',
      description: 'Integrated student information system with course enrollment, grading workflows, tuition billing, and alumni portal.',
      organizationId: 'org-global',
      managerId: 'usr-pm-marcus',
      managerName: 'Marcus Holloway',
      teamIds: ['team-apps', 'team-data'],
      status: 'planning',
      priority: 'P2',
      riskLevel: 'low',
      riskScore: 15,
      riskFactors: ['Discovery phase complete', 'Requirements signed off by academic council'],
      startDate: pastDays(10),
      targetDate: futureDays(90),
      budgetHours: 420,
      createdAt: pastDays(10),
      updatedAt: pastDays(3),
    },
  ];

  // ── Realistic Tasks across Projects ──
  const tasks: Task[] = [
    // E-Commerce Platform Tasks
    {
      id: 'task-ecom-101',
      projectId: 'proj-ecom',
      title: 'Stripe & PayPal Multi-Currency Payment Gateway Integration',
      description: 'Implement resilient webhook listeners, 3D-Secure 2.0 authentication, idempotency keys, and automated refund handlers.',
      column: 'In Progress',
      priority: 'P0',
      assigneeId: 'usr-emp-david',
      assignee: 'David Chen',
      reporterId: 'usr-pm-marcus',
      reporter: 'Marcus Holloway',
      dueDate: futureDays(5),
      estimatedHours: 40,
      actualHours: 28,
      tags: ['Payments', 'Security', 'Backend'],
      dependencies: [],
      riskLevel: 'medium',
      riskNotes: 'Awaiting updated sandbox credentials from EU payment provider.',
      createdAt: pastDays(20),
      updatedAt: pastDays(1),
    },
    {
      id: 'task-ecom-102',
      projectId: 'proj-ecom',
      title: 'Real-time Redis Inventory Sync during Flash Sales',
      description: 'Develop distributed locking mechanism using Redlock to prevent overselling across cluster instances during concurrency spikes.',
      column: 'Review',
      priority: 'P0',
      assigneeId: 'usr-lead-sarah',
      assignee: 'Sarah Jenkins',
      reporterId: 'usr-pm-marcus',
      reporter: 'Marcus Holloway',
      dueDate: futureDays(2),
      estimatedHours: 32,
      actualHours: 30,
      tags: ['Performance', 'Inventory', 'Redis'],
      dependencies: ['task-ecom-101'],
      riskLevel: 'low',
      riskNotes: 'Load testing verified 5,000 req/sec with zero stock race conditions.',
      createdAt: pastDays(18),
      updatedAt: pastDays(0),
    },
    {
      id: 'task-ecom-103',
      projectId: 'proj-ecom',
      title: 'Automated Tax Calculation Engine (Avalara / TaxJar Connector)',
      description: 'Calculate state and municipal sales tax dynamically based on postal jurisdiction and tax category exemptions.',
      column: 'To Do',
      priority: 'P1',
      assigneeId: 'usr-emp-david',
      assignee: 'David Chen',
      reporterId: 'usr-lead-sarah',
      reporter: 'Sarah Jenkins',
      dueDate: futureDays(12),
      estimatedHours: 24,
      actualHours: 4,
      tags: ['Tax', 'Compliance', 'API'],
      dependencies: [],
      riskLevel: 'low',
      riskNotes: 'Standard REST interface documentation reviewed.',
      createdAt: pastDays(12),
      updatedAt: pastDays(2),
    },
    {
      id: 'task-ecom-104',
      projectId: 'proj-ecom',
      title: 'Abandoned Cart Email & Push Notification Workflow',
      description: 'Trigger scheduled recovery sequences 1hr and 24hr after cart abandonment with personalized discount token.',
      column: 'Done',
      priority: 'P2',
      assigneeId: 'usr-dev-priya',
      assignee: 'Priya Sharma',
      reporterId: 'usr-pm-marcus',
      reporter: 'Marcus Holloway',
      dueDate: pastDays(2),
      estimatedHours: 16,
      actualHours: 14,
      tags: ['Marketing', 'Automation'],
      dependencies: [],
      riskLevel: 'low',
      createdAt: pastDays(25),
      updatedAt: pastDays(2),
    },
    {
      id: 'task-ecom-105',
      projectId: 'proj-ecom',
      title: 'Elasticsearch Product Catalog Auto-complete & Faceted Search',
      description: 'Deploy search query scoring, typo tolerance, multi-language stemming, and price range facets.',
      column: 'Backlog',
      priority: 'P1',
      assigneeId: 'usr-dev-priya',
      assignee: 'Priya Sharma',
      reporterId: 'usr-pm-marcus',
      reporter: 'Marcus Holloway',
      dueDate: futureDays(20),
      estimatedHours: 36,
      actualHours: 0,
      tags: ['Search', 'Elasticsearch'],
      dependencies: [],
      riskLevel: 'low',
      createdAt: pastDays(10),
      updatedAt: pastDays(10),
    },

    // Hospital Management System Tasks (High Risk)
    {
      id: 'task-hosp-201',
      projectId: 'proj-hosp',
      title: 'HL7 FHIR Patient Health Records Ingestion Pipeline',
      description: 'Parse clinical document architecture (CDA) XML and FHIR JSON feeds into normalized patient record models.',
      column: 'Blocked',
      priority: 'P0',
      assigneeId: 'usr-dev-priya',
      assignee: 'Priya Sharma',
      reporterId: 'usr-pm-marcus',
      reporter: 'Marcus Holloway',
      dueDate: pastDays(3),
      estimatedHours: 50,
      actualHours: 42,
      tags: ['FHIR', 'Healthcare', 'Compliance'],
      dependencies: [],
      riskLevel: 'high',
      riskNotes: 'Blocked by third-party hospital lab API mTLS cert expiration.',
      createdAt: pastDays(40),
      updatedAt: pastDays(0),
    },
    {
      id: 'task-hosp-202',
      projectId: 'proj-hosp',
      title: 'Emergency Department Real-Time Bed Triage Dashboard',
      description: 'Interactive ward map rendering bed occupancy status, patient acuity scores, and cleaning schedule alerts.',
      column: 'In Progress',
      priority: 'P0',
      assigneeId: 'usr-lead-sarah',
      assignee: 'Sarah Jenkins',
      reporterId: 'usr-pm-marcus',
      reporter: 'Marcus Holloway',
      dueDate: pastDays(1),
      estimatedHours: 45,
      actualHours: 38,
      tags: ['Emergency', 'Frontend', 'SSE'],
      dependencies: [],
      riskLevel: 'high',
      riskNotes: 'Task is overdue by 1 day; critical milestone for Phase 1 clinical trial.',
      createdAt: pastDays(30),
      updatedAt: pastDays(0),
    },
    {
      id: 'task-hosp-203',
      projectId: 'proj-hosp',
      title: 'Pharmacy Dispensing Barcode Verification & Audit Log',
      description: 'Enforce two-stage verification on high-risk medication dispensing with pharmaceutical inventory reconciliation.',
      column: 'Review',
      priority: 'P1',
      assigneeId: 'usr-emp-david',
      assignee: 'David Chen',
      reporterId: 'usr-lead-sarah',
      reporter: 'Sarah Jenkins',
      dueDate: futureDays(3),
      estimatedHours: 28,
      actualHours: 26,
      tags: ['Pharmacy', 'Audit', 'Safety'],
      dependencies: [],
      riskLevel: 'medium',
      createdAt: pastDays(22),
      updatedAt: pastDays(1),
    },
    {
      id: 'task-hosp-204',
      projectId: 'proj-hosp',
      title: 'HIPAA Audit Trail Storage & Immutable Encryption',
      description: 'Store every EHR access event in tamper-proof cryptographic audit log with KMS envelope encryption.',
      column: 'Done',
      priority: 'P0',
      assigneeId: 'usr-org-admin',
      assignee: 'Eleanor Sterling',
      reporterId: 'usr-super-admin',
      reporter: 'Alexander Vance',
      dueDate: pastDays(10),
      estimatedHours: 35,
      actualHours: 32,
      tags: ['Security', 'Encryption', 'HIPAA'],
      dependencies: [],
      riskLevel: 'low',
      createdAt: pastDays(50),
      updatedAt: pastDays(10),
    },

    // Mobile Banking Application Tasks
    {
      id: 'task-mbank-301',
      projectId: 'proj-mbank',
      title: 'Biometric Authentication (FaceID / TouchID) & Secure Enclave',
      description: 'Store device public keys in hardware security module and issue short-lived JWT tokens on biometric confirmation.',
      column: 'Review',
      priority: 'P0',
      assigneeId: 'usr-lead-sarah',
      assignee: 'Sarah Jenkins',
      reporterId: 'usr-pm-marcus',
      reporter: 'Marcus Holloway',
      dueDate: futureDays(6),
      estimatedHours: 30,
      actualHours: 25,
      tags: ['Mobile', 'Security', 'Biometrics'],
      dependencies: [],
      riskLevel: 'low',
      riskNotes: 'Security pen-test passed with zero vulnerabilities.',
      createdAt: pastDays(24),
      updatedAt: pastDays(1),
    },
    {
      id: 'task-mbank-302',
      projectId: 'proj-mbank',
      title: 'Instant P2P Money Transfers with Fraud Heuristic Scoring',
      description: 'Implement real-time settlement engine with velocity limits, geo-anomaly detection, and SMS confirmation triggers.',
      column: 'In Progress',
      priority: 'P0',
      assigneeId: 'usr-emp-david',
      assignee: 'David Chen',
      reporterId: 'usr-pm-marcus',
      reporter: 'Marcus Holloway',
      dueDate: futureDays(8),
      estimatedHours: 40,
      actualHours: 22,
      tags: ['Banking', 'Fraud', 'Transfers'],
      dependencies: ['task-mbank-301'],
      riskLevel: 'low',
      createdAt: pastDays(15),
      updatedAt: pastDays(0),
    },
    {
      id: 'task-mbank-303',
      projectId: 'proj-mbank',
      title: 'Virtual Credit Card Provisioning & Google/Apple Pay Push',
      description: 'Generate dynamic CVV tokens and push card metadata directly to Apple Wallet and Google Pay via Mastercard MDES.',
      column: 'To Do',
      priority: 'P1',
      assigneeId: 'usr-dev-priya',
      assignee: 'Priya Sharma',
      reporterId: 'usr-lead-sarah',
      reporter: 'Sarah Jenkins',
      dueDate: futureDays(18),
      estimatedHours: 35,
      actualHours: 0,
      tags: ['Cards', 'ApplePay', 'GooglePay'],
      dependencies: [],
      riskLevel: 'low',
      createdAt: pastDays(10),
      updatedAt: pastDays(10),
    },
    {
      id: 'task-mbank-304',
      projectId: 'proj-mbank',
      title: 'Transaction History Categorization & Spending Analytics',
      description: 'Automatically categorize card transactions into dining, utilities, groceries, and travel with monthly budgets.',
      column: 'Done',
      priority: 'P2',
      assigneeId: 'usr-emp-david',
      assignee: 'David Chen',
      reporterId: 'usr-pm-marcus',
      reporter: 'Marcus Holloway',
      dueDate: pastDays(5),
      estimatedHours: 20,
      actualHours: 18,
      tags: ['Analytics', 'Budgeting'],
      dependencies: [],
      riskLevel: 'low',
      createdAt: pastDays(28),
      updatedAt: pastDays(5),
    },

    // College Management Portal Tasks
    {
      id: 'task-campus-401',
      projectId: 'proj-campus',
      title: 'Online Course Registration & Prerequisite Validation Engine',
      description: 'Validate GPA thresholds, credit caps, and prerequisite chain before permitting course seat reservation.',
      column: 'To Do',
      priority: 'P1',
      assigneeId: 'usr-emp-david',
      assignee: 'David Chen',
      reporterId: 'usr-pm-marcus',
      reporter: 'Marcus Holloway',
      dueDate: futureDays(22),
      estimatedHours: 32,
      actualHours: 6,
      tags: ['Academics', 'Enrollment'],
      dependencies: [],
      riskLevel: 'low',
      createdAt: pastDays(8),
      updatedAt: pastDays(1),
    },
    {
      id: 'task-campus-402',
      projectId: 'proj-campus',
      title: 'Faculty Grade Submission & Transcript PDF Generator',
      description: 'Build grading portal with rubric calculations, dean approval workflow, and digitally signed PDF transcripts.',
      column: 'Backlog',
      priority: 'P2',
      assigneeId: 'usr-dev-priya',
      assignee: 'Priya Sharma',
      reporterId: 'usr-pm-marcus',
      reporter: 'Marcus Holloway',
      dueDate: futureDays(35),
      estimatedHours: 28,
      actualHours: 0,
      tags: ['Grading', 'PDF', 'Faculty'],
      dependencies: [],
      riskLevel: 'low',
      createdAt: pastDays(8),
      updatedAt: pastDays(8),
    },
  ];

  // ── Timesheets ──
  const timesheets: TimesheetEntry[] = [
    {
      id: 'ts-101',
      userId: 'usr-emp-david',
      userName: 'David Chen',
      projectId: 'proj-ecom',
      projectName: 'E-Commerce Platform',
      taskId: 'task-ecom-101',
      taskTitle: 'Stripe & PayPal Multi-Currency Payment Gateway Integration',
      date: dateOnly(-1),
      hours: 7.5,
      description: 'Implemented webhook signature verification and 3DS challenge handling.',
      status: 'approved',
      createdAt: pastDays(1),
    },
    {
      id: 'ts-102',
      userId: 'usr-lead-sarah',
      userName: 'Sarah Jenkins',
      projectId: 'proj-ecom',
      projectName: 'E-Commerce Platform',
      taskId: 'task-ecom-102',
      taskTitle: 'Real-time Redis Inventory Sync during Flash Sales',
      date: dateOnly(-1),
      hours: 6.0,
      description: 'Benchmarked distributed lock under 10k simulated concurrent checkout calls.',
      status: 'approved',
      createdAt: pastDays(1),
    },
    {
      id: 'ts-103',
      userId: 'usr-dev-priya',
      userName: 'Priya Sharma',
      projectId: 'proj-hosp',
      projectName: 'Hospital Management System',
      taskId: 'task-hosp-201',
      taskTitle: 'HL7 FHIR Patient Health Records Ingestion Pipeline',
      date: dateOnly(-2),
      hours: 8.0,
      description: 'Debugged FHIR Bundle parser edge cases for oncology pathology reports.',
      status: 'logged',
      createdAt: pastDays(2),
    },
    {
      id: 'ts-104',
      userId: 'usr-emp-david',
      userName: 'David Chen',
      projectId: 'proj-mbank',
      projectName: 'Mobile Banking Application',
      taskId: 'task-mbank-302',
      taskTitle: 'Instant P2P Money Transfers with Fraud Heuristic Scoring',
      date: dateOnly(0),
      hours: 5.5,
      description: 'Engineered daily velocity threshold rule matrix and SMS verification dispatcher.',
      status: 'logged',
      createdAt: pastDays(0),
    },
    {
      id: 'ts-105',
      userId: 'usr-lead-sarah',
      userName: 'Sarah Jenkins',
      projectId: 'proj-mbank',
      projectName: 'Mobile Banking Application',
      taskId: 'task-mbank-301',
      taskTitle: 'Biometric Authentication (FaceID / TouchID) & Secure Enclave',
      date: dateOnly(-3),
      hours: 7.0,
      description: 'Finalized Secure Enclave key generation and biometric signature validation.',
      status: 'approved',
      createdAt: pastDays(3),
    },
  ];

  // ── Audit Logs / Activities ──
  const activities: Activity[] = [
    {
      id: 'act-1',
      timestamp: pastDays(0),
      userId: 'usr-lead-sarah',
      userName: 'Sarah Jenkins',
      userRole: 'team_lead',
      action: 'task_moved',
      targetType: 'task',
      targetId: 'task-ecom-102',
      targetTitle: 'Real-time Redis Inventory Sync during Flash Sales',
      details: 'Sarah Jenkins moved "Real-time Redis Inventory Sync during Flash Sales" from In Progress to Review.',
    },
    {
      id: 'act-2',
      timestamp: pastDays(1),
      userId: 'usr-emp-david',
      userName: 'David Chen',
      userRole: 'employee',
      action: 'time_logged',
      targetType: 'timesheet',
      targetId: 'ts-101',
      targetTitle: 'E-Commerce Platform',
      details: 'David Chen logged 7.5 hours on Stripe & PayPal Gateway Integration.',
    },
    {
      id: 'act-3',
      timestamp: pastDays(1),
      userId: 'usr-pm-marcus',
      userName: 'Marcus Holloway',
      userRole: 'project_manager',
      action: 'task_updated',
      targetType: 'task',
      targetId: 'task-hosp-201',
      targetTitle: 'HL7 FHIR Patient Health Records Ingestion Pipeline',
      details: 'Marcus Holloway updated risk level to HIGH and added vendor blocking notes.',
    },
    {
      id: 'act-4',
      timestamp: pastDays(2),
      userId: 'usr-org-admin',
      userName: 'Eleanor Sterling',
      userRole: 'org_admin',
      action: 'user_created',
      targetType: 'user',
      targetId: 'usr-viewer-rachel',
      targetTitle: 'Rachel Adams',
      details: 'Eleanor Sterling provisioned stakeholder audit access for Rachel Adams (Viewer role).',
    },
    {
      id: 'act-5',
      timestamp: pastDays(2),
      userId: 'usr-org-admin',
      userName: 'Eleanor Sterling',
      userRole: 'org_admin',
      action: 'project_created',
      targetType: 'project',
      targetId: 'proj-campus',
      targetTitle: 'College Management Portal',
      details: 'Eleanor Sterling created project "College Management Portal" under global organization.',
    },
    {
      id: 'act-6',
      timestamp: pastDays(3),
      userId: 'usr-lead-sarah',
      userName: 'Sarah Jenkins',
      userRole: 'team_lead',
      action: 'task_assigned',
      targetType: 'task',
      targetId: 'task-mbank-302',
      targetTitle: 'Instant P2P Money Transfers with Fraud Heuristic Scoring',
      details: 'Sarah Jenkins assigned task to David Chen.',
    },
  ];

  // ── Notifications ──
  const notifications: Notification[] = [
    {
      id: 'notif-1',
      userId: 'usr-emp-david',
      title: 'Task Assigned',
      message: 'You have been assigned to "Instant P2P Money Transfers with Fraud Heuristic Scoring".',
      type: 'info',
      link: '/tasks',
      read: false,
      createdAt: pastDays(0),
    },
    {
      id: 'notif-2',
      userId: 'usr-pm-marcus',
      title: 'Project Risk Alert',
      message: 'Hospital Management System risk elevated to HIGH due to 3 overdue compliance tasks.',
      type: 'alert',
      link: '/projects',
      read: false,
      createdAt: pastDays(0),
    },
    {
      id: 'notif-3',
      userId: 'usr-lead-sarah',
      title: 'Task Ready for Review',
      message: '"Real-time Redis Inventory Sync during Flash Sales" was moved to Review by David Chen.',
      type: 'info',
      link: '/kanban',
      read: true,
      createdAt: pastDays(1),
    },
    {
      id: 'notif-4',
      userId: 'all',
      title: 'System Maintenance Notice',
      message: 'Scheduled backup and data indexing completed successfully.',
      type: 'success',
      link: '/dashboard',
      read: true,
      createdAt: pastDays(3),
    },
  ];

  const settings: SystemSettings = {
    organizationName: 'Nexus Enterprise Solutions',
    allowSelfRegistration: false,
    defaultTheme: 'dark',
    sessionTimeoutHours: 24,
    mlRiskThresholds: {
      high: 65,
      medium: 35,
    },
    lastSeedReset: now.toISOString(),
  };

  return {
    columns: structuredClone(DEFAULT_COLUMNS),
    tasks,
    projects,
    users,
    teams,
    timesheets,
    activities,
    notifications,
    settings,
    theme: 'dark',
  };
}
